### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(FingertipDrop)
add_subdirectory(FingertipDropContent)
add_subdirectory(App)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    FingertipDropplugin
    FingertipDropContentplugin)